export const COLOR_MAP = new Map();

COLOR_MAP.set("normal", "#A0A29F");
COLOR_MAP.set("fighting", "#D3425F");
COLOR_MAP.set("flying", "#A1BBEC");
COLOR_MAP.set("poison", "#B763CF");
COLOR_MAP.set("ground", "#DA7C4D");
COLOR_MAP.set("rock", "#C9BB8A");
COLOR_MAP.set("bug", "#92BC2C");
COLOR_MAP.set("ghost", "#5F6DBC");
COLOR_MAP.set("steel", "#5695A3");
COLOR_MAP.set("fire", "#FBA54C");
COLOR_MAP.set("water", "#539DDF");
COLOR_MAP.set("grass", "#5FBD58");
COLOR_MAP.set("electric", "#F2D94E");
COLOR_MAP.set("psychic", "#FA8581");
COLOR_MAP.set("ice", "#75D0C1");
COLOR_MAP.set("dragon", "#0C69C8");
COLOR_MAP.set("dark", "#595761");
COLOR_MAP.set("fairy", "#EE90E6");
COLOR_MAP.set("shadow", "#111827");
COLOR_MAP.set("unknown", "#0f172a");
